/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _XAT_H_RPCGEN
#define _XAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct linea_xat {
	char *linea;
};
typedef struct linea_xat linea_xat;

#define PROGRAMA_XAT 0x20000001
#define VERSION_XAT 1

#if defined(__STDC__) || defined(__cplusplus)
#define write 1
extern  int * write_1(linea_xat *, CLIENT *);
extern  int * write_1_svc(linea_xat *, struct svc_req *);
#define getChat 2
extern  linea_xat * getchat_1(void *, CLIENT *);
extern  linea_xat * getchat_1_svc(void *, struct svc_req *);
extern int programa_xat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define write 1
extern  int * write_1();
extern  int * write_1_svc();
#define getChat 2
extern  linea_xat * getchat_1();
extern  linea_xat * getchat_1_svc();
extern int programa_xat_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_linea_xat (XDR *, linea_xat*);

#else /* K&R C */
extern bool_t xdr_linea_xat ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_XAT_H_RPCGEN */
